### GET all deck ids
GET http://localhost:5959/decks

### GET Decklist (list of cards in deck with specific id)
GET http://localhost:5959/decks/670436a50a8cb9ea3989b1ee

### get
GET http://localhost:5959/cards

### modify action
PUT http://localhost:5959/actions/671813dae0184ef41c0250f7 HTTP/1.1
Content-Type: application/json

{
  "displayText": "This is a modified Action",
  "actionType": "Modify",
  "actionValue": 2
}

### post action
POST http://localhost:5959/actions HTTP/1.1
Content-Type: application/json

{
  "displayText": "Show this example text to your opponent.",
  "actionType": "Display",
  "actionValue": 1
}

### post card
POST http://localhost:5959/cards HTTP/1.1
Content-Type: application/json

{
  "name": "Weed em and Reap",
  "type": "Attack",
  "energyCost": 3,
  "shopValue": 75,
  "color": "gold",
  "actions": [
    {
      "actionId": "671813dae0184ef41c0250f7",
      "quantity": 2
    },
    {
      "actionId": "67180c0745669034f841e112",
      "quantity": 1
    }
  ]
}

### modify card
PUT http://localhost:5959/cards/67195ad1e03a776db96acfe1 HTTP/1.1
Content-Type: application/json

{
  "name": "Modified Card",
  "type": "Really Modified",
  "energyCost": 0,
  "shopValue": 1,
  "color": "red",
  "actions": [
    {
      "actionId": "671813dae0184ef41c0250f7",
      "quantity": 1
    }
  ]
}

### delete card
DELETE http://localhost:5959/cards/67195677d7109aa7a8c0fa8c HTTP/1.1

### remove action
DELETE http://localhost:5959/actions/67181a20cadd2e0110e54921 HTTP/1.1

### POST add deck
POST http://localhost:5959/decks HTTP/1.1
Content-Type: application/json

{
  "name": "New Deck 01",
  "cards": [
    {
      "cardId": "671967e154bf4d6a02be6644",
      "quantity": 1
    }
  ]
}

### PUT Modify Card
PUT http://localhost:5959/deck/670592a8adf45cd53f814a02/67058e0d2646e56aed2a180b HTTP/1.1
Content-Type: application/json

{
  "actions": [
      {
        "type": "Damage",
        "value": 27
      },
      {
        "type": "Block",
        "value": 30
      }
    ],
    "valueShop": 460,
    "quantity": 3,
    "cardType": "Attack",
    "cost": 5,
    "border": "violet",
    "deckId": "670592a8adf45cd53f814a02"
}

### modify deck
PUT http://localhost:5959/decks/670436a50a8cb9ea3989b1ee HTTP/1.1
Content-Type: application/json

{
  "name": "New Deck",
  "cards": [
    {
      "cardId": "671967e154bf4d6a02be6644",
      "quantity": 4
    },
    {
      "cardId": "67195ad1e03a776db96acfe1",
      "quantity": 2
    }
  ]
}

### DELETE card from deck
DELETE http://localhost:5959/decks/67198f88385d4a78cd638825 HTTP/1.1

# Production
# Production
# Production
# Production
# Production
# Production
# Production
# Production
### GET all deck ids
GET https://cse341-project-1-p1v7.onrender.com/deck

### GET Decklist (list of cards in deck with specific id)
GET https://cse341-project-1-p1v7.onrender.com/deck/670436a50a8cb9ea3989b1ee

### POST Card (Add card to deck)
POST https://cse341-project-1-p1v7.onrender.com/deck/670592a8adf45cd53f814a02 HTTP/1.1
Content-Type: application/json

{
  "actions": [
    {
      "type": "Buff",
      "value": 50
    },
    {
      "type": "Block",
      "value": 50
    }
  ],
  "valueShop": 300,
  "quantity": 1,
  "cardType": "Skill",
  "cost": 3,
  "border": "gold",
  "deckId": "670592a8adf45cd53f814a02"
}

### POST add deck
POST https://cse341-project-1-p1v7.onrender.com/deck HTTP/1.1
Content-Type: application/json

{
    "name": "New Deck"
}

### PUT Modify Card
PUT https://cse341-project-1-p1v7.onrender.com/deck/670592a8adf45cd53f814a02/67058e0d2646e56aed2a180b HTTP/1.1
Content-Type: application/json

{
  "actions": [
      {
        "type": "Damage",
        "value": 27
      },
      {
        "type": "Block",
        "value": 30
      }
    ],
    "valueShop": 460,
    "quantity": 3,
    "cardType": "Attack",
    "cost": 5,
    "border": "violet",
    "deckId": "670592a8adf45cd53f814a02"
}

### DELETE card from deck
DELETE https://cse341-project-1-p1v7.onrender.com/deck/670436a50a8cb9ea3989b1ee/67047dad2803b937a72648d2 HTTP/1.1